# Permalinks
permalink:        pretty

# Setup
url:              http://oldskywolf.github.io

# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl:         '' 

title:           oldskywolf 

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:      >
 Every French soldier carries a marshal's baton in his knapsack
# The tags listed as entries in the sidebar
sidebar_tags:     [iOS,Ruby,RE]

# Fallback image and color if not overwritten for tag or post
image:            /public/img/nap.jpg
color:            '#A85641'

author:
  name:           'oldskywolf'
  github:         oldskywolf 
  photo:          http://qwtel.com/public/img/flo.jpg

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:          |
    Hi, I'm oldskywolf, who is an iOS engineer.
